### ISSUE TITLE
После пропуска трека показывается неверный статус

### ISSUE THREAD

**Issue by vpolikarpov** [vladertel/tg_dj#5]
Это происходит из-за того, что запрос пропуска трека выполняется асинхронно.

Варианты решения:
1. Сделать запрос пропуска синхронным
2. Обновлять информацию у администраторов при каждой смене трека
3. Подставлять информацию о текущем треке в ответе на запрос пропуска уже новые данные

**Comment by vladertel** [comment]
второй вариант мне нравится больше всего
а ты что думаешь? @Preveter 
Если ты солидарен, ща сделаю

**Comment by vladertel** [comment]
сделал по другому вообще, но норм работает
