### ISSUE TITLE
Тред, в котором возникло исключение, тихо отваливается и не перезапускается

### ISSUE THREAD

**Issue by vpolikarpov** [vladertel/tg_dj#6]
Если в каком-то из тредов возникает необработанное исключение, то тред просто тихо исчезает без каких-либо уведомлений или записей в лог, что крайне затрудняет отладку

**Comment by vladertel** [comment]
перенаправил stderr в stdout, может поможет

**Comment by vpolikarpov** [comment]
Проблема потеряла актуальность с переходом на asyncio
